apiVersion: apps/v1
kind: ReplicaSet
metadata: // <1>
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec: // <2>
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels: // <3>
      tier: frontend
  template:  // <4>
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
