
:toc:
== Docker

=== Overview

.Containers
Basically there are a few Linux kernal features : "namespaces" & "control groups a.k.a cgroups" that let you isolate process from each other. Basically when you use these features you call it as "Containers". Basically these features let you pretend you have something like a virtual machine, except it’s not a virtual machine at all, it’s just processes running in the same Linux kernel. “Docker containers” uses these features

Docker in short is a tool box for developers, sysadmin to deploy their application in sandbox a.k.a containers to run on the host OS.

.Benefits
- package an application with all of its dependencies into a standardized unit 
- less overhead and more efficient usage of system and resources

.VM
The industry standard today is to use Virtual Machines (VMs) to run software applications. VMs run applications inside a guest Operating System, which runs on virtual hardware powered by the server’s host OS.

VMs are great at providing full process isolation for applications: there are very few ways a problem in the host operating system can affect the software running in the guest operating system, and vice-versa. But this isolation comes at great cost — the computational overhead spent virtualizing hardware for a guest OS to use is substantial.


.Basic Terminology
Frequently in the Docker ecosystem.

- Images - The blueprints of our application which form the basis of containers. It is a read only template that contains a set of instructions to create a container. In the demo above, we used the docker pull command to download the busybox image.
- Containers - Runnable instance of the image which has its own resources, networking from the parent host OS machine. Created from Docker images and run the actual application. We create a container using docker run which we did using the busybox image that we downloaded. A list of running containers can be seen using the docker ps command.
- Docker Daemon - The background service running on the host that manages building, running and distributing Docker containers. The daemon is the process that runs in the operating system to which clients talk to.
- Docker Client - The command line tool that allows the user to interact with the daemon. More generally, there can be other forms of clients too - such as Kitematic which provide a GUI to the users.
- Docker Hub - A registry of Docker images. You can think of the registry as a directory of all available Docker images. If required, one can host their own Docker registries and can use them for pulling images.

=== Docker Commands

.Basic commands
[options="header,footer"]
|=======================
|Command|Description
|docker pull `<IMAGE_NAME>`    |Pulls the image from docker registry ans saves it to our system 
|docker images   |list off all images in our system
|docker container run `<IMAGE NAME>`   |run a docker container. Behind the scenes :

    * Docker client finds the image (e.g. busybox0
    * loads up the container
    * then runs a command in that container

we run docker run busybox, we didn't provide a command, so the container boots up, run an empty command and then exit
run command with the `-it` flags attaches us to an interactive tty in the container
|docker ps    |shows you all containers that are currently running.
when you run docker ps -a it displays list of all containers that we ran
|docker rm <container id>

docker rm $(docker ps -a -q -f status=exited) |removes the containers
|docker container prune |removes all stopped containers
|docker-machine ip default |get the ip address If you're using docker-toolbox
| |
|=======================

=== Docker Compose

.What?
Compose is a tool that is used for defining and running multi-container Docker apps in an easy way. It provides a configuration file called docker-compose.yml that can be used to bring up an application and the suite of services it depends on with just one command. Compose works in all environments: production, staging, development, testing, as well as CI workflows, although Compose is ideal for development and testing environments.


=== FAQ
* Q: How do we tell one container about the other container and get them to talk to each other?
  A: short answer is docker network

When docker is installed, it creates three networks automatically.

-----------------
$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
c2c695315b3a        bridge              bridge              local
a875bec5d6fd        host                host                local
ead0e804a67b        none                null                local
-----------------

The bridge network is the network in which containers are run by default

In the Docker ecosystem, however, there are a bunch of other open-source tools which play very nicely with Docker. A few of them are -

    Docker Machine - Create Docker hosts on your computer, on cloud providers, and inside your own data center
    Docker Compose - A tool for defining and running multi-container Docker applications.
    Docker Swarm - A native clustering solution for Docker
    Kubernetes - Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications.

[NOTE]
====
So really at this point, that's what Docker is about: running processes. Now Docker offers a quite rich API to run the processes: shared volumes (directories) between containers (i.e. running images), forward port from the host to the container, display logs, and so on. But that's it: Docker as of now, remains at the process level.

While it provides options to orchestrate multiple containers to create a single "app", it doesn't address the managemement of such group of containers as a single entity. And that's where tools such as Fig come in: talking about a group of containers as a single entity. Think "run an app" (i.e. "run an orchestrated cluster of containers") instead of "run a container".

====


